src/Entity/Comment.php
<?php

namespace App\Entity;

use App\Repository\CommentRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommentRepository::class)]
class Comment
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $content = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $datetime;


    #[ORM\ManyToOne(inversedBy: 'comments')]
    private ?Video $video = null;


    #[ORM\Column(length: 255)]
    private ?string $Author = null;

    #[ORM\ManyToOne(inversedBy: 'comments')]
    private ?User $User = null;

    public function __construct()
    {

    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getDatetime(): ?\DateTimeInterface
    {
        return $this->datetime;
    }

    public function setDatetime(\DateTimeInterface $datetime): self
    {
        $this->datetime = $datetime;

        return $this;
    }


    public function getVideo(): ?Video
    {
        return $this->video;
    }

    public function setVideo(?Video $video): self
    {
        $this->video = $video;

        return $this;
    }


    public function getAuthor(): ?string
    {
        return $this->Author;
    }

    public function setAuthor(string $Author): self
    {
        $this->Author = $Author;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }





}

templates/movies/landingPage.html.twig
{% extends "home/base.html.twig" %}
{% block head %}
    {{ parent() }}
    <link rel="stylesheet" href="/styles/comments.css" />
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>

{% endblock %}
{% block content %}
    <div class="section" style="padding-top: 0;">
        <div class="hero-slide-item">
            <img src="{{ video.thumbnail }}" alt="">
            <div class="overlay"></div>
            <div class="hero-slide-item-content">
                <div class="item-content-wrapper">
                    <div class="item-content-title">
                        {{ video.title }}
                    </div>

                    <div class="movie-infos">
                        <div class="movie-info">
                            <i class="bx bxs-star"></i>
                            <span>{{ video.rating }}</span>
                        </div>
                        <div class="movie-info">
                            <i class="bx bxs-time"></i>
                            <span>{{ video.duration }}</span>
                        </div>
                        <div class="movie-info">
                            <span>{{ video.releaseYear }}</span>
                        </div>
                    </div>
                    <div class="item-content-description">
                        {{ video.description }}
                    </div>
                    <div class="item-action">
                        <a href="/video/play/{{video.id}}" class="btn btn-hover">
                            <i style="margin-right: 5px" class="bx bxs-right-arrow"></i>
                            <span>Watch now</span>
                        </a>
                        <br>
                        <br>
                        {% if username %}
                            {% if is_favorite %}
                                <a href="{{ path('video_favorite', {'id': video.id}) }}" class="btn btn-hover">
                                    <i style="margin-right: 5px" class='bx bxs-star' ></i>
                                    <span>Remove from favorites</span>
                                </a>
                            {% else %}
                                <a href="{{ path('video_favorite', {'id': video.id}) }}" class="btn btn-hover">
                                    <i style="margin-right: 5px" class='bx bx-star' ></i>
                                    <span>Add to favorites</span>

                                </a>
                            {% endif %}
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="hero-slide-item-image ">
              <iframe width="560" height="315" src="{{ video.filepath }}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
            </div>
        </div>
    </div>

    </div> <!--comment sectio-->
    <!-- LATEST MOVIES SECTION
    <div class="section">
        <div class="container">
            <div class="section-header">
                similar movies
            </div>
            <div class="movies-slide carousel-nav-center owl-carousel">
                <a href="#" class="movie-item">
                    <img src="https://fr.web.img2.acsta.net/medias/nmedia/18/62/81/09/18784915.jpg" alt="">
                    <div class="movie-item-content">
                        <div class="movie-item-title">
                            Theatre of the dead
                        </div>
                        <div class="movie-infos">
                            <div class="movie-info">
                                <i class="bx bxs-star"></i>
                                <span>9.5</span>
                            </div>
                            <div class="movie-info">
                                <i class="bx bxs-time"></i>
                                <span>120 mins</span>
                            </div>
                            <div class="movie-info">
                                <span>HD</span>
                            </div>
                            <div class="movie-info">
                                <span>16+</span>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
        </div>
    </div>
    -->


{% endblock %}

templates/movies/videoPage.html.twig
{% extends "home/base.html.twig" %}
{% block head %}
    {{ parent() }}
    <link rel="stylesheet" href="/styles/comments.css" />
{% endblock %}
{% block content %}

<div style="padding-top: 100px;" class="container" >
    <div  class="section-header" >
        {{ video.title }}
    </div>
    <div class="hero-slide-item">
        <iframe style="position: absolute;top: 0; right: 0;bottom: 0; left: 0;margin: auto;" width="100%" height="100%" src="{{ video.filepath }}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
    </div>
    <div  class="section-header" style="margin-top: 50px" >
        Comments
    </div>
</div>
    <main>
       <div class="comment-section">

           {% if app.user %}
                    {{ form_start(form) }}
           <div class="comment-wrp" style="border: 1px solid #ccc;border-radius: 8px;margin-bottom: 1rem;">
               <div class="c-container c-user">
                   <span class="input-group-icon"><i class='bx bxs-user'></i></span>
                   <p class="usr-name">{{ username }}</p>
               </div>
                    <div class="input-group">
      {{ form_widget(form.content, { 'attr': {'class': 'form-control', 'placeholder': 'Add a comment...'} }) }}
                <button type="submit" class="bu-primary">Submit</button>
  </div>
           </div>
                {{ form_end(form) }}

           {% else %}
               <div style="margin-bottom: 1rem;border: 1px solid hsl(358, 79%, 66%);border-radius: 8px;padding: 10px;">
               <p style="color: hsl(358, 79%, 66%);padding: 10px;"><i class=' bx bx-error'></i>You need to <a href="{{ path('app_user_login') }}"> <u style="color: hsl(358, 79%, 66%)">log in</u> </a> to comment.</p>
               </div>
           {% endif %}
            {% for comment in comments %}
            <div class="comment-wrp">
                <div class="comment c-container">
                    <div class="c-controls">
                        {% if app.user and app.user == comment.user %}
                            <a href="{{ path('video_comment_delete', {id: comment.id}) }}" onclick="return confirm('Are you sure you want to delete this comment ?')" class="delete"><i class='bx bx-trash' ></i>delete</a>
                        {% endif %}                    </div>
                    <div class="c-user">
                        <span class="input-group-icon"><i class='bx bxs-user'></i></span>
                        <p class="usr-name">{{ comment.author }}</p>
                        <p class="cmnt-at">{{ comment.datetime|date('F j, Y, g:i a') }}</p>
                    </div>
                    <p class="c-text">
                        <span class="c-body">{{ comment.content }}</span>
                    </p>
                </div>
                {% endfor %}
            </div>
            <!--commentS wrapper-->

        </div> <!--comment section-->
    </main>
{% endblock %}
